-- 초기 스키마.
--
-- 기존 개발 DB에는 ddl-auto: update가 만들어 둔 같은 테이블이 이미 있다.
-- IF NOT EXISTS로 두어 새 환경과 기존 환경 모두에서 그대로 돌아가게 한다.
-- 다음 마이그레이션(V2~)부터는 평범하게 작성한다.

CREATE TABLE IF NOT EXISTS chat_sessions (
    session_id VARCHAR(64)  NOT NULL,
    user_id    VARCHAR(64),
    title      VARCHAR(200) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_chat_sessions PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id   VARCHAR(64) NOT NULL,
    role         VARCHAR(20) NOT NULL,
    content      TEXT        NOT NULL,
    sources_json TEXT,
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (message_id),
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions (session_id)
);

-- 사이드바 조회: 특정 사용자의 대화방을 최근 순으로 페이지 단위로 읽는다.
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_updated
    ON chat_sessions (user_id, updated_at DESC);

-- 대화 내역 조회와 최근 맥락 조회가 모두 이 순서를 쓴다.
-- FK 컬럼에 인덱스가 없으면 대화방 삭제 시 자식 테이블을 전부 훑는다.
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_created
    ON chat_messages (session_id, created_at, message_id);
